use_frameworks!

target 'WelcomeAboard_Example' do
  pod 'WelcomeAboard', :path => '../'

  target 'WelcomeAboard_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.0'
    pod 'iOSSnapshotTestCase' , '~> 6.2.0'
    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
